server:
  port: 8083
spring:
 cloud:
   gateway:
     routes:
       - id: swiggy-app
         uri: lb://SWIGGY-CONSUMER-SERVICE
         predicates:
           - Path=/swiggy/**
         filters:
           - AuthenticationFilter


       - id: restaurant-service
         uri: lb://RESTAURANT-PRODUCER-SERVICE
         predicates:
           - Path=/restaurant/**
         filters:
           - AuthenticationFilter

       - id: security-service
         uri: lb://JWT-SECURITY-SERVICE
         predicates:
           - Path=/auth/**

 application:
   name: SWIGGY-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/